### ISSUE TITLE
Remove logo in navbar

### ISSUE THREAD

**Issue by 4allprograms** [projectsend/projectsend#1142]
Do you mind to tell me how to remove logo at navbar?

**Comment by ignacionelson** [comment]
Add this code to a css file, or a css asset (using the new assets manager) with this

`.navbar-brand svg {
	display:none !important;
}`

Copy these settings

![image](https://user-images.githubusercontent.com/6926562/197105420-62fb7545-dbb4-4841-ac91-0e64ede2f3dd.png)

**Comment by ignacionelson** [comment]
Hope that helps!

**Comment by confidentcyber** [comment]
Is it possible to put the custom uploaded logo to the NAVbar and favicon?

**Comment by ignacionelson** [comment]
Hi @confidentcyber . It's not possible to do that in PS. What you can do is modify the files and remember to do that again when you update or reinstall.
Check includes/layout/header-top.php, line 14

<?php include_once ROOT_DIR.'/assets/img/ps-icon.svg'; ?>

You can change that to an <img> or <svg> of your choice, or overwrite ps-icon.svg with your own.

Regarding favicons, they are located at assets/img/favicon/
You may replace the files there with your own. Hope that helps

**Comment by betullam** [comment]
> Is it possible to put the custom uploaded logo to the NAVbar and favicon?

Hi,

I managed to add a custom logo in the navbar like this:

1. Upload a logo file to your server so that you can access it with an URL, e. g.: https://example.org/logo.png

2. Create a custom CSS in "Tools" --> "Custom HTML/CSS/JS" --> "New CSS". Activate checkbox "Enabled". Set "Location" to "All locations" and "Position" to "In \<head\>".

3. Add this CSS:
   ```
   .navbar-header::before {
     max-height: 27px;
     max-width: 27px;
     content: url(https://example.org/logo.png);
     display: inline-block;
     margin-left: 5px;
   }
   ```

4. To center all things in the navbar, add also this CSS:
   ```
   .navbar-header {
     display: flex;
     align-items: center;
   }
   ```
