### ISSUE TITLE
download counter

### ISSUE THREAD

**Issue by onlinestatements** [projectsend/projectsend#386]
Sometimes my customers like to download a file right after they have uploaded it so as to test it to make sure it really got uploaded. But when they do this the file gets marked as downloaded even in the admin account the file is marked as downloaded and sometimes I miss downloading some files because they are already marked as downloaded.
Is there a way to make it so when the client clicks their file to download it doesn't show as being downloaded on the admin side.
But I still want it to show as downloaded on my side only if I download the file myself.

Thanks

**Comment by lenamtl** [comment]
System user upload file it should not be counted....
Client does...
You will have to modify the code...
You will have to think about the logical in which circumstances you want the download to be counted.

**Comment by dannyulman** [comment]
Actually one of you guys helped me a few months back and told me what code to change to make it so when the system user clicks on a file to download it now marks it as downloaded. I forget who helped me. I think it might have been Ignacio. We just emailed instead of using the github.

I want to now make it so when a normal user clicks on their file it will NOT mark it as downloaded because I might not download it if I see its marked as downloaded already. I have missed some files in the past few months because the customer downloaded them and marked them as downloaded. We get a couple hundred files every day so it's hard to keep track of whats been downloaded if the customer already downloaded it themselves.

**Comment by onlinestatements** [comment]
> System user upload file it should not be counted.... Client does... You will have to modify the code... You will have to think about the logical in which circumstances you want the download to be counted.

does the new 1335 version have the ability to make it so when a user downloads their own file on their end that it will NOT mark it as downloaded. I only want files to be marked as downloaded whenever a system user or admin user downloads them.
We keep missing files when downloading because they are already marked as downloaded when our customer downloads it themselves. They do this because they like to verify the upload went thru all the way.

I am still on the old r754 version but will be updating to 1335 in the next several months.

Thank You

**Comment by ignacionelson** [comment]
@onlinestatements Sorry for the delay, added an option to ignore logging downloads of the file's author here df7f107
This will be available in the next release.
