### ISSUE TITLE
Client Upload - No Notification Email Sent

### ISSUE THREAD

**Issue by gpm1** [projectsend/projectsend#527]
version - r754

Hi

most of the email notifications are working, but i cannot get an email notification sent if a client uploads a file, despite the upload page displaying "Email notifications have been sent"

Within System Options, i have set the following:

- From Address - myemail@email.com
- Send copies>When a system user uploads files - checked
- Send copies>When a client uploads files - checked
- Send copies>Address supplied above (on "From") - checked
- Also to this addresses - differentemail@email.com
- PHP Mail (Basic) is selected

as i mentioned most emails do work, e.g. registration email, password reset, when admin uploads and assigns file to a client.   these all work so i know there are no issues with email config.

Please can you advise if this is a bug or some sort of config issue

thanks

**Comment by rcs27** [comment]
I have been dealing with this issue for several month, and finally I found what I call "the issue",(I am not a programmer or expert coding) after several observation, I discover that the clients (tbl_users) without the "create_by" value wont send the notification went they upload the files and those who had the "create_by" filled with the admin user value, works perfectly. 

Solution you can try. open your phpMyAdmin, open tbl_users, click Browse (you can verify that the value on "Created_by" is empty, if you want to try this fix, update the "created_by" value  with the admin username. login with the client credentials, upload any file and check if you get the notification. IMPORTANT: I use SMTP Gmail, with PHPMailer some clients report that the notifications from us were going to spam folder. ok, once you make sure is working, go backup to phpMyAdmin, on the tbl_users, click SQL and use this:

UPDATE tbl_users
SET created_by = 'type your admin username'
WHERE level = 0;

I user level = 0 because is the only value in common for all the clients.

That's it!!! now I am getting all notification when client upload their files.
maybe and expert can fix this issue or can investigate more about it.

**Comment by gpm1** [comment]
@rcs27 Thanks for identifying a workaround.  it would appear that the within systems admin login that there should be an option to assign clients to account manager, so that when a client uploads a file that the relevant account manager gets the email notification rather than the systems admin.

If you change created_by to be the username of an account manager (as per your sql above), then the account manager gets the email notification.

@ignacionelson when you get to this, can you advise what the fix will be.   Will it be

1. always send to Systems Admin (and any others specified in System Options>Email Notifications), or
2. allow systems admin (or account managers) to assign, or claim a client

thanks again for good work

**Comment by rcs27** [comment]
@gpm1 
If you change created_by to be the username of an account manager (as per your sql above), then the account manager gets the email notification.
A:// Yes, I have tried Administrator, account manager and Uploader and all of them got the notifications when created_by field has any this user, if the field is empty then I dont get any notification when client upload a file.
UPDATE: those client who self-register wont get any value on  "created_by" then I dont get any notification from them, so far I have to to the update manually as above.

**Comment by achleitner** [comment]
problem is `$this->this_admin = get_current_user_username();` in actions-clients.php

**Comment by ignacionelson** [comment]
Solved in r1265
