### ISSUE TITLE
auto logoff

### ISSUE THREAD

**Issue by johanpeters** [projectsend/projectsend#584]
implement auto logoff (time based) and browser close based.
whenever a user does not actively on the website.. after x minutes auto logoff.

when user closes browser (or browser tab) then auto logoff..

**Comment by mschop** [comment]
PHP does already provide garbage collection of unused sessions. You can configure this by setting php configuration values like 'session.gc_maxlifetime'.
Closing the session, when a user closes the browser can be achieved by setting the php setting 'session.cookie_lifetime=0'. This should remove the cookie, when the browser is closed (please test this, as I'm not sure on this).

**Comment by johanpeters** [comment]
okay.. greate.. good to know.. 
would be nice to have this in the configuration options.. not everyone is used to edit config files..

**Comment by johanpeters** [comment]
btw.. GDRP requires to give the user a cookie option to accept / deny cookies.

**Comment by mschop** [comment]
see #569 

We could add it, but this has several implications. Some linux distributions handle it differently and there is a lot, that can go wrong with this. Therefore I would not like to implement such feature.

**Comment by johanpeters** [comment]
i have tried the php.ini settings.. 
when i close the browser completly.. the session is closed and you need to login again.
when you only close a tab and not the browser.. session keeps active.. no new login.

this is a security issue.. not al users will nicely close the browser or lock there system.. 

i use for a other client rainloop.. and the have implemented it somehow.. 
close tab.. then new logon
close browser.. then new logon
session timeout .. then new logon.


the maflifetime does not work.. set it on 20.. wait 4 minits... then click in the menu.. session still active and no relogin message..

**Comment by mschop** [comment]
@johanpeters please don't forget to reopen an issue when adding further messages. Otherwise your message could get lost.

This is not a security issue as this is expected behaviour. Why should this be a security issue?

Regarding maxlifetime -> Which server OS or distribution are you running? The php session gc does not run on every request and is dependent on the variables gc_probability and gc_divisor. On some distributions those options are ignored and an independent cron job runs the gc. So either the cron did not run or there were not enough php executions so that gc_probability / gc_divisor did not fire gc.
