### ISSUE TITLE
Use X-Accel (XSendFile) with projectsend? - NGINX

### ISSUE THREAD

**Issue by Skyridr** [projectsend/projectsend#824]
The new function XSendFile, is it compatible with nginx (X-Accel)? If so, can anyone give an example how to make it work?

**Comment by ignacionelson** [comment]
I've added the xsendfile option when developing under apache, and forgot to adjust for nginx after switching!
I'll work on this and add it as soon as possible.

**Comment by Skyridr** [comment]
Awesome, thank you!

**Comment by ignacionelson** [comment]
I think I got it. I've pushed the changes to the repository but haven't made a new release yet. I have a few more items in the milestone that I want to complete before that. If you want to test it, please download the master branch from this repository. The only thing to take into account is that zip files now have to be generated inside /upload/temp so that directory needs to have write permissions for the php server user. Hope that helps!

**Comment by Skyridr** [comment]
Do you have, by any chance an example config rules for nginx?

**Comment by ignacionelson** [comment]
![xaccel](https://user-images.githubusercontent.com/6926562/98814865-132bb500-2405-11eb-8f47-6adfd3630922.png)

It will show you the code you need to use when you select the option :) 
Please let me know if it worked!

**Comment by Skyridr** [comment]
Thanks, I wish to try it out. But I noticed quite the file size difference between the original version (20MB+) and the current master of 2.8MB. Do the files still needs to be compiled?

**Comment by ignacionelson** [comment]
When you download from github, the dependencies are not included, so you need to get them and compile the assets. However, there were no changes to the assets and deps since r1270 so if you are updating an existing installation you could just overwrite what you have and PS will load the already installed ones.

**Comment by Skyridr** [comment]
The example box:

![image](https://user-images.githubusercontent.com/6794064/98829016-045ef580-2439-11eb-983a-df54772ec3d0.png)

(with the text) is not something I see:

![image](https://user-images.githubusercontent.com/6794064/98829086-150f6b80-2439-11eb-93cf-741d66c08fab.png)

I tried setting its location to upload/files (where the files are located) with the rest of the var directory accordingly. But I keep getting ERR_INVALID_RESPONSE when attempting to download the file with it being enabled.

**Comment by ignacionelson** [comment]
My bad! The box is hidden and shown via js, but since you have the old assets it's not showing. I'll send you a link to a full download

**Comment by ignacionelson** [comment]
https://www.projectsend.org/direct-download/projectsend-r1277.zip

**Comment by Skyridr** [comment]
Thanks! See it correctly now. However, the original I've set was correct. Getting:

```
This site can’t be reachedThe webpage at https://website/download.php?id=2&token=L6F0fmdV5L1zalMnqr090Zr3vqaOLaAf&download might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
```

**Comment by ignacionelson** [comment]
This happens only with xaccel enabled, and after clicking the download button right? Or are you getting the issue as soon as  you try to load the page?

**Comment by Skyridr** [comment]
Only when I click the lovely download button. The rest works normally. And yes, only with X enabled. Disabling makes the download work as usual.

**Comment by Skyridr** [comment]
Any update by any chance?

**Comment by ignacionelson** [comment]
r1295 is out and includes this feature. Thanks for the suggestion!
