### ISSUE TITLE
Preview function yields 403

### ISSUE THREAD

**Issue by chewy-chewbacca** [projectsend/projectsend#847]
Great work on the new version! We had our provider lock down the uploads/files folder when we installed the previous version as it allowed anyone to see the files in there if they guessed the filename. In the new version it seems the preview function accesses the file directly and is yielding a 403 error due to what we believe are our restrictions. Is it proper practice to leave these folders open to the world? Everything else works fine it's just the preview that's broken.

Inspecting the preview iframe, I see the file is a direct link
<iframe src="https://ourprojectsenddomain.com/portal//upload/files/1605814550-54ddc507817ddecc1a175b7dbdeb9b9b49e67351-205d5f90-bf30-4caa-97ff-e876e0d4d00a.pdf"></iframe>

Thanks again for the great system!

**Comment by chewy-chewbacca** [comment]
We had the provider reverse the change and the preview now works, as does the branding images which we found were also broken. So that issue is fixed.

However - is it normal in a standard configuration for the public to be able to access any file in the /uploads/files folder by name? i.e. https://ourprojectsenddomain.com/portal/upload/files/1605814550-54ddc507817ddecc1a175b7dbdeb9b9b49e67351-205d5f90-bf30-4caa-97ff-e876e0d4d00a.pdf

If we upload a file, get the name and bring up an incognito window we can directly access this file.

Once the provider reverted the security these files are now public, not browsable but public. I realize that the file name is completely unguessable, but I just wanted to make sure we are secure as possible, while working within the constraints of ProjectSend.

**Comment by ignacionelson** [comment]
Hi! Glad you got this working.

Indeed, this is one of the reasons why a full rewrite of the app is needed.
The current way is not ideal but it's there since the beginning and I never found a consistent way to change it with an update without breaking some -or most- existing installations (like for example cases where PS is not at root level, which I assume are most of them).
Uploaded files should be saved in a folder above the public root (like, for example, Moodle or Laravel apps do), so they are not accessible via browser. 

Regarding the file name, you could only read it on the database or by doing a var dump on the file object. If you get a preview of the file you also get it, but by that point you already logged the users intentions. This is, again, far from ideal. It's just something that it not solvable without a full rewrite.

I've been working on this rewrite of PS for a while but it's far from being usable.
The main problem is working on an importer for existing installations, but above all, the difference in how this systems would be installed.
Today, PS could be dropped in any directory and it works, much like WordPress for example. This makes the installation very easy, accessible and drops the technical knowledge required to have it running. Changing this for the sake of PS will be very hard to  explain to existing, non-technical users and I've been stuck with this decision for a while.

**Comment by chewy-chewbacca** [comment]
Well I still love the product. Maybe you could explore an option for storage in AWS S3 or something else so you break the dependency on the website folders needing security at all.

**Comment by chewy-chewbacca** [comment]
Not to go off topic, I can start another issue, but it seems while the email test works, we are getting no notifications of uploads, etc. with the new version.

**Comment by ignacionelson** [comment]
S3 integration would be great indeed. It's been suggested and I never got around to work on it. I'll try to give it a higher priority!

**Comment by ignacionelson** [comment]
Oh, you are not getting ANY emails? Did this happen with r1270 too?

**Comment by chewy-chewbacca** [comment]
We were on the last stable release r1070 and emailing worked fine, we upgraded to the latest today. We use G-Suite to relay and the test within ProjectSend works fine. Just not anything beyond that like upload notifications.

**Comment by chewy-chewbacca** [comment]
Should I close this issue (resolved) and start a new regarding email for better visibility?

**Comment by ignacionelson** [comment]
Yes, please open a new one, Thanks!
