### ISSUE TITLE
Social Login - External login

### ISSUE THREAD

**Issue by sz2000** [projectsend/projectsend#872]
Hello,
I tried to update the version following the guide.
All right, I just can't restore the google login.
If I enable the Google social login, the Google button appears at login, but pressing it takes me to the link
https://mysite/process.php?do=social_login&provider=google but blank page.
I have not found a way to enable a debug that indicates any errors.
I upgraded php from 7.2 to 7.4.
Do you have any suggestions?
thanks

**Comment by sz2000** [comment]
In the process.php file added to line 21:
`error_reporting(E_ALL | E_STRICT); ini_set('display_errors', 'On');`
to print errors.

subsequently i installed the missing package:
apt install php7.4-mbstring

**Comment by ignacionelson** [comment]
Thanks for the heads up! I've added the module to the requirements list in the README and the home page.

**Comment by TjebbeVQ** [comment]
I have a similar issue but with the windows authentication.
I'm guessing WindowsLive acctually means O365 authentication.

Using the above mentioned error printing I get following error:

`Fatal error: Uncaught Hybridauth\Exception\InvalidApplicationCredentialsException: Your application id is required in order to connect to WindowsLive in /data/sites/web/TEST/www/upl/vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php:253 Stack trace: #0 /data/sites/web/TEST/www/upl/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php(109): Hybridauth\Adapter\OAuth2->configure() #1 /data/sites/web/TEST/www/upl/vendor/hybridauth/hybridauth/src/Hybridauth.php(141): Hybridauth\Adapter\AbstractAdapter->__construct() #2 /data/sites/web/TEST/www/upl/vendor/hybridauth/hybridauth/src/Hybridauth.php(101): Hybridauth\Hybridauth->getAdapter() #3 /data/sites/web/TEST/www/upl/includes/Classes/Auth.php(133): Hybridauth\Hybridauth->authenticate() #4 /data/sites/web/TEST/www/upl/process.php(27): ProjectSend\Classes\Auth->socialLogin() #5 {main} thrown in /data/sites/web/TEST/www/upl/vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php on line 253`

It looks to me like the application cannot retrieve the AppID or Secret key which is entered in the settings.

Quoting the ID's does not help. But using the ID's from O365 in Google or Facebook actually attempts to login via those providers but is unable since it's not a valid App ID (since it's the one from O365)...

Any guide to get Windows authentication working? We are running the latest version r1295.

Thanks
